name: open_weather_flutter_app
description: A demo Flutter app that shows the current weather for the user’s location.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '^3.0.0'

dependencies:
  dio: ^5.4.0
  equatable: ^2.0.5
  firebase_auth: ^4.15.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.9
  geolocator: ^10.1.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - .env