name: open_weather_flutter_app
description: A demo Flutter app that shows the current weather for the user’s location.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '^3.0.0'

dependencies:
  equatable: ^2.0.5
  firebase_auth: ^4.15.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/